### ISSUE TITLE
Caelum2 missing from the LewisShort.ttl

### ISSUE THREAD

**Issue by nevenjovanovic** [CIRCSE/LewisShort#1]
In the LewisShort.ttl file there is "caelum1" <http://lila-erc.eu/data/lexicalResources/LewisShort/id/LexComponent/n6041.0>, but no "caelum2". In Lewis Short entry for caelum https://logeion.uchicago.edu/caelum the first meaning is "the chisel or burin of the sculptor or engraver, a graver" (lemma https://lila-erc.eu/data/id/lemma/97622). The much more frequent meaning "the sky, heaven, the heavens, the vault of heaven" seems to be missing from the ttl file. Consequently, the lemma for caelum "sky" <https://lila-erc.eu/data/id/lemma/92231> in the Text Linker and in the Query interface is confusingly linked to the following lexical resources:
```
Lexical resources:

Etymological Dictionary of Latin (Brill)
Language PIE: *keh₂i‑lo‑
Language PIt: *kailo‑
LatinAffectus
Polarity Positive
Polarity Value 0.5
Lewis and Short Latin Dictionary
the chisel or burin of the sculptor or engraver , a graver .

```
To avoid confusion during lemmatization, either the link of caelum to "chisel" should be removed, or the sense for caelum2 should be added and linked to caelum <https://lila-erc.eu/data/id/lemma/92231>.

**Comment by gersh0m** [comment]
The real issue is in the documentation: it is not specified that the LewisShort.ttl file it is a PARTIAL version of the dictionary! not all its entries are exported mainly because of 'under specification' of the xml source.
It is  work in progress: future version will be more complete.
